SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '1246434f4d7506d0' HASH '2ad027a269e5e8e5db80ec1f789a8d27597ddf21a2171494c441bd2375942f6b' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "USER_ID" VARCHAR(254) NOT NULL,
    "ENCRYPTED_PASSWORD" VARCHAR(100) NOT NULL,
    "NAME" VARCHAR(60) NOT NULL,
    "ROLE" VARCHAR(12) NOT NULL,
    "CLASSROOM" CHAR(4),
    "CLASS_NUMBER" CHAR(2),
    "DARK_MODE" BOOLEAN DEFAULT FALSE NOT NULL,
    "REGISTER_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REGISTER_USER_ID" VARCHAR(254) NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    "UPDATE_USER_ID" VARCHAR(254),
    "ENABLED" BOOLEAN DEFAULT TRUE,
    "NUMBER_OF_TRIALS" INT DEFAULT 0 NOT NULL,
    "USER_STATUS" INT DEFAULT 1 NOT NULL
);               
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("USER_ID");   
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
('t-ukeire@hcs.ac.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', STRINGDECODE('\u5b89\u90e8\u83ef\u5948'), 'ROLE_TEACHER', 'S3A1', NULL, FALSE, TIMESTAMP '2021-11-30 09:49:48.236948', 't-ukeire@hcs.ac.jp', NULL, NULL, TRUE, 0, 1),
('s-ukeire@hcs.ac.jp', '$2a$10$xRTXvpMWly0oGiu65WZlm.3YL95LGVV2ASFjDhe6WF4.Qji1huIPa', STRINGDECODE('\u77f3\u7530\u60a0\u4ecb'), 'ROLE_STUDENT', 'S3A1', '01', FALSE, TIMESTAMP '2021-11-30 09:49:48.241935', 't-ukeire@hcs.ac.jp', NULL, NULL, TRUE, 0, 1);               
CREATE MEMORY TABLE "PUBLIC"."JOB_HUNTING"(
    "APPLY_ID" VARCHAR(254) NOT NULL,
    "APPLICANT_ID" VARCHAR(254) NOT NULL,
    "CONTENT" VARCHAR(2) NOT NULL,
    "COMPANY_NAME" VARCHAR(137) NOT NULL,
    "STATUS" VARCHAR(2) DEFAULT '2' NOT NULL,
    "APPLY_TYPE" CHAR(1) NOT NULL,
    "INDICATE" VARCHAR(254)
);              
ALTER TABLE "PUBLIC"."JOB_HUNTING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("APPLY_ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.JOB_HUNTING;             
CREATE MEMORY TABLE "PUBLIC"."REQUESTS"(
    "APPLY_ID" VARCHAR(254) NOT NULL,
    "DATE_ACTIVITY_FROM" TIMESTAMP NOT NULL,
    "DATE_ACTIVITY_TO" TIMESTAMP NOT NULL,
    "LOC" VARCHAR(100) NOT NULL,
    "WAY" CHAR(1) NOT NULL,
    "DATE_ABSENCE_FROM" TIMESTAMP,
    "DATE_ABSENCE_TO" TIMESTAMP,
    "LEAVE_EARLY_DATE" TIMESTAMP,
    "ATTENDANCE_DATE" TIMESTAMP,
    "REMARK" VARCHAR(254),
    "REGISTER_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REGISTER_USER_ID" VARCHAR(254) NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    "UPDATE_USER_ID" VARCHAR(254)
);        
ALTER TABLE "PUBLIC"."REQUESTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("APPLY_ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REQUESTS;
CREATE MEMORY TABLE "PUBLIC"."REPORTS"(
    "APPLY_ID" VARCHAR(254) NOT NULL,
    "ADVANCE_OR_RETREAT" BOOLEAN NOT NULL,
    "REMARK" VARCHAR(254),
    "REGISTER_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REGISTER_USER_ID" VARCHAR(254) NOT NULL,
    "UPDATE_DATE" TIMESTAMP,
    "UPDATE_USER_ID" VARCHAR(254)
); 
ALTER TABLE "PUBLIC"."REPORTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("APPLY_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REPORTS; 
CREATE MEMORY TABLE "PUBLIC"."SUMMARY_COMPANIES"(
    "COMPANY_ID" VARCHAR(254) NOT NULL,
    "JOB_NO" VARCHAR(254),
    "COMPANY_NAME" VARCHAR(137),
    "RESUME" BOOLEAN DEFAULT FALSE NOT NULL,
    "UNIVERSITY_TRANRIPTSSCRIPTS" BOOLEAN DEFAULT FALSE NOT NULL,
    "UNIVERSITY_DIPLOMA" BOOLEAN DEFAULT FALSE NOT NULL,
    "HCS_TRANSCRIPT" BOOLEAN DEFAULT FALSE NOT NULL,
    "HCS_DIPLOMA" BOOLEAN DEFAULT FALSE NOT NULL,
    "HEALTH_CERTIFICATE" BOOLEAN DEFAULT FALSE NOT NULL,
    "HIGH_SCHOOL_TRANSCRIPT" BOOLEAN DEFAULT FALSE NOT NULL,
    "RECOMMENDATION" BOOLEAN DEFAULT FALSE NOT NULL,
    "PERSONAL_INFORMATION_AGREEMENT" BOOLEAN DEFAULT FALSE NOT NULL
);           
ALTER TABLE "PUBLIC"."SUMMARY_COMPANIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("COMPANY_ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUMMARY_COMPANIES;       
CREATE MEMORY TABLE "PUBLIC"."SUMMARY_DOCUMENTS"(
    "APPLY_ID" VARCHAR(254) NOT NULL,
    "COMPANY_ID" VARCHAR(254),
    "RECEIPT_OF_RESUME" TIMESTAMP,
    "RECEIPT_OF_UNIVERSITY_TRANRIPTSSCRIPTS" TIMESTAMP,
    "RECEIPT_OF_UNIVERSITY_DIPLOMA" TIMESTAMP,
    "RECEIPT_OF_HCS_TRANSCRIPT" TIMESTAMP,
    "RECEIPT_OF_HCS_DIPLOMA" TIMESTAMP,
    "RECEIPT_OF_HEALTH_CERTIFICATE" TIMESTAMP,
    "RECEIPT_OF_HIGH_SCHOOL_TRANSCRIPT" TIMESTAMP,
    "RECEIPT_OF_RECOMMENDATION" TIMESTAMP,
    "RECEIPT_OF_PERSONAL_INFORMATION_AGREEMENT" TIMESTAMP,
    "RECEIPT_OF_ALL_REQUIRED" TIMESTAMP
);           
ALTER TABLE "PUBLIC"."SUMMARY_DOCUMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("APPLY_ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUMMARY_DOCUMENTS;       
CREATE MEMORY TABLE "PUBLIC"."EVENTS"(
    "EVENT_ID" VARCHAR(254) NOT NULL,
    "COMPANY_NAME" VARCHAR(137) NOT NULL,
    "DATETIME" TIMESTAMP NOT NULL,
    "LOC" VARCHAR(100) NOT NULL,
    "CONTENT" VARCHAR(254) NOT NULL,
    "BRING" VARCHAR(254),
    "REGISTER_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REGISTER_USER_ID" VARCHAR(254) NOT NULL,
    "UPDATE_DATE" TIMESTAMP DEFAULT NULL,
    "UPDATE_USER_ID" VARCHAR(254) DEFAULT NULL
);              
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("EVENT_ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENTS;  
CREATE MEMORY TABLE "PUBLIC"."SUMMARY_LIST_MANAGEMENT"(
    "APPLY_ID" VARCHAR(254) NOT NULL,
    "REGISTER_DATE" TIMESTAMP,
    "REGISTER_USER_ID" VARCHAR(254) NOT NULL
);              
ALTER TABLE "PUBLIC"."SUMMARY_LIST_MANAGEMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("APPLY_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUMMARY_LIST_MANAGEMENT; 
CREATE MEMORY TABLE "PUBLIC"."MESSAGES"(
    "MESSAGE_ID" VARCHAR(254) NOT NULL,
    "USER_ID" VARCHAR(254) NOT NULL,
    "EVENT_ID" VARCHAR(254),
    "SUBJECT" VARCHAR(254) NOT NULL,
    "CONTENT" VARCHAR(254),
    "IS_CHECKED" BOOLEAN DEFAULT FALSE NOT NULL,
    "SENDER_ID" VARCHAR(254) NOT NULL,
    "RECEIVED_DATE" TIMESTAMP
);         
ALTER TABLE "PUBLIC"."MESSAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_13" PRIMARY KEY("MESSAGE_ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MESSAGES;
CREATE MEMORY TABLE "PUBLIC"."REPORT_HOGE"(
    "REPORT_ID" INT NOT NULL,
    "JOB_NUMBER" VARCHAR(13),
    "USER_ID" VARCHAR(254),
    "CLASSROOM" CHAR(4),
    "CLASS_NUMBER" CHAR(2),
    "NAME" VARCHAR(60),
    "COURSE_CODE" CHAR(1),
    "COMPANY_NAME" VARCHAR(60),
    "COMPANY_NAME_KANA" CHAR(3),
    "DATETIME" DATE,
    "PLACE" VARCHAR(60),
    "ENTRY_SECTION" VARCHAR(6),
    "ENTRY_SECTION_OTHER" VARCHAR(60),
    "VENUE_SECTION" VARCHAR(6),
    "VENUE_SECTION_OTHER" VARCHAR(60),
    "TEST_SECTION" VARCHAR(6),
    "TEST_FINAL" BOOLEAN DEFAULT FALSE,
    "TEST_SECTION_OTHER" VARCHAR(60),
    "TEST_SUMMARY" VARCHAR(6),
    "TEST_SUMMARY_OTHER" VARCHAR(60),
    "RESULT_NOTIFICATION" VARCHAR(2),
    "SUCCESS_ONLY" BOOLEAN DEFAULT FALSE,
    "RESULT_NOTIFICATION_DAY" INT,
    "APTITUDE_TEST_DETAIL" VARCHAR(6),
    "APTITUDE_TEST_DETAIL_OTHER" VARCHAR(60),
    "INTERVIEW_DETAIL" VARCHAR(6),
    "INTERVIEW_DETAIL_OTHER" VARCHAR(60),
    "INTERVIEW_NUMBER" INT,
    "INTERVIEWER_NUMBER" INT,
    "INTERVIEWER_POSITION" VARCHAR(60),
    "INTERVIEW_TIME" INT,
    "THEME" VARCHAR(60),
    "QUESTION_CONTENTS" VARCHAR(60),
    "REPORT_STATUS" VARCHAR(2) DEFAULT '1',
    "REGISTERED_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REQUEST_DATE" DATE,
    "REGISTERED_USER_ID" VARCHAR(254),
    "REMARKS" VARCHAR(254)
);
ALTER TABLE "PUBLIC"."REPORT_HOGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_73" PRIMARY KEY("REPORT_ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REPORT_HOGE;             
ALTER TABLE "PUBLIC"."REPORTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6C" FOREIGN KEY("APPLY_ID") REFERENCES "PUBLIC"."JOB_HUNTING"("APPLY_ID") NOCHECK;         
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FK_UPDATE_USER_ID" FOREIGN KEY("UPDATE_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") ON DELETE CASCADE NOCHECK;      
ALTER TABLE "PUBLIC"."SUMMARY_LIST_MANAGEMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FF" FOREIGN KEY("APPLY_ID") REFERENCES "PUBLIC"."JOB_HUNTING"("APPLY_ID") NOCHECK;         
ALTER TABLE "PUBLIC"."JOB_HUNTING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A9" FOREIGN KEY("APPLICANT_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7A9" FOREIGN KEY("UPDATE_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;          
ALTER TABLE "PUBLIC"."MESSAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_131" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;               
ALTER TABLE "PUBLIC"."REQUESTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_173" FOREIGN KEY("REGISTER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;      
ALTER TABLE "PUBLIC"."SUMMARY_DOCUMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_52" FOREIGN KEY("APPLY_ID") REFERENCES "PUBLIC"."JOB_HUNTING"("APPLY_ID") NOCHECK;               
ALTER TABLE "PUBLIC"."SUMMARY_LIST_MANAGEMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FFF" FOREIGN KEY("REGISTER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."REPORTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6C0" FOREIGN KEY("REGISTER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."REQUESTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_17" FOREIGN KEY("APPLY_ID") REFERENCES "PUBLIC"."JOB_HUNTING"("APPLY_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."REPORTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6C09" FOREIGN KEY("UPDATE_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7A" FOREIGN KEY("REGISTER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;         
ALTER TABLE "PUBLIC"."SUMMARY_DOCUMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_527" FOREIGN KEY("COMPANY_ID") REFERENCES "PUBLIC"."SUMMARY_COMPANIES"("COMPANY_ID") NOCHECK;    
ALTER TABLE "PUBLIC"."MESSAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_131AF" FOREIGN KEY("SENDER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;           
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FK_REGISTER_USER_ID" FOREIGN KEY("REGISTER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") ON DELETE CASCADE NOCHECK;  
ALTER TABLE "PUBLIC"."MESSAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_131A" FOREIGN KEY("EVENT_ID") REFERENCES "PUBLIC"."EVENTS"("EVENT_ID") NOCHECK;           
ALTER TABLE "PUBLIC"."REQUESTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1735" FOREIGN KEY("UPDATE_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;       
